Squares/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Squares.Security;
using Squares.Models.ViewModel;
using Squares.Models.EntityManager;

namespace Squares.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        [AuthorizeRoles("Administrator")]
        public ActionResult Index()
        {
            SetDataView setDataView = SetManager.GetSetDataView();

            return View(setDataView);
        }
    }
}

Squares/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Squares.Models.ViewModel;
using Squares.Models.EntityManager;

namespace Squares.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            SetDataView setDataView = SetManager.GetSetDataView();

            return View(setDataView);
        }

        public ActionResult LikeDislikeSet(int setID)
        {
            CurrentUser currentUser = UserManager.GetCurrentUser();

            if (currentUser == null)
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);

            bool setAlreadyLiked = SetManager.IsSetLiked(setID, currentUser.UserID);

            if (setAlreadyLiked)
                SetManager.DislikeSet(setID, currentUser.UserID);
            else
                SetManager.LikeSet(setID, currentUser.UserID);

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

Squares/Controllers/SetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Squares.Models.ViewModel;
using Squares.Models.DB;
using Squares.Models.EntityManager;
using System.Data.SqlTypes;
using System.Web.Helpers;
using Squares.Helpers;

namespace Squares.Controllers
{
    public class SetController : Controller
    {
        // GET: Set
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        // GET: Set Combine
        public ActionResult Combine(int? id)
        {
            if (id == null)
                return RedirectToAction("Index", "Home");

            SetCombineView setCombineView = SetManager.GetSetCombineView((int) id);

            if (setCombineView.Set == null)
                return RedirectToAction("Index", "Home");

            return View(setCombineView);
        }

        public IEnumerable<SelectListItem> GetCategories()
        {
            List<SelectListItem> categories = CategoryManager.GetCategoriesForDropDown();
            return new SelectList(categories, "Value", "Text");
        }

        // GET: Create Set
        [HttpGet]
        public ActionResult Create()
        {
            SetCreateView setCreateView = new SetCreateView();
            setCreateView.Categories = GetCategories();

            return View(setCreateView);
        }

        private void CreatePieces()
        {
            Set insertedSet = SetManager.GetLatestInsertedSet();

            int pieceNumber = 1;
            string imageName = "";
            string imageFormat = "";

            foreach (string requestFileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[requestFileName];
                //Save file content goes here
                if (file != null && file.ContentLength > 0)
                {
                    string path = Request.MapPath("~/Content/img/sets/set" + insertedSet.SetID);

                    bool isExists = System.IO.Directory.Exists(path);
                    if (!isExists)
                        System.IO.Directory.CreateDirectory(path);

                    WebImage image = new WebImage(file.InputStream);
                    image.FileName = "set" + insertedSet.SetID + "-pic" + pieceNumber;

                    if (pieceNumber == 1)
                        SetManager.UpdateSetCoverImage(insertedSet.SetID, image.FileName + "." + image.ImageFormat);
                    

                    // For some reason the WebImage changes its FileName on save, so I have to
                    // save theese in a variable to use them to create a piece in the db later on.
                    imageName = image.FileName;
                    imageFormat = image.ImageFormat;

                    image.Save(path + "/" + imageName);
                }

                Piece piece = new Piece();
                piece.PieceTitle = "PieceTitle Test!";
                piece.PieceImage = imageName + "." + imageFormat;
                piece.PieceSetID = insertedSet.SetID;
                PieceManager.CreatePiece(piece);

                pieceNumber++;
            }
        }

        // POST: Create Set
        [HttpPost]
        public ActionResult Create(SetCreateView setCreateView)
        {
            CurrentUser currentUser = UserManager.GetCurrentUser();

            Set set = new Set();
            set.SetTitle = setCreateView.SetTitle;
            set.SetDescription = setCreateView.SetDescription;
            set.SetCreatedDate = DateTime.Now;
            set.SetCategoryID = setCreateView.SelectedCategory;
            set.SetUserID = currentUser.UserID;
            set.SetCoverImage = "";
            SetManager.CreateSet(set);

            CreatePieces();

            return Json(Url.Action("Index", "Home")); // Christian skal sørge for at redirecte ved hjælp af : window.location.href i den metode som modtager dette response.
        }

        // POST: Delete Set
        [HttpPost]
        [NoDirectAccess]
        public ActionResult Delete(int id)
        {
            CurrentUser currentUser = UserManager.GetCurrentUser();
            Set set = SetManager.GetSetByID(id);

            if (set.SetUserID != currentUser.UserID)
                return RedirectToAction("Index", "Home");

            SetManager.DeleteSet(id);

            return Json(new { success = true });
        }
    }
}

Squares/Views/Home/Index.cshtml
@using Squares.Helpers
@model Squares.Models.ViewModel.SetDataView

@{
    ViewBag.Title = "Discover sets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section SocialMetaTags {
    <meta property="og:url" content="http://squaresapp.azurewebsites.net/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Squares" />
    <meta property="og:description" content="Squares is a digital gallery for new art, where you can fashion and create the final expression of the art pieces." />
    <meta property="og:image" content="@HtmlExtensions.FullyQualifiedUri("~/Content/img/page/about.jpg")" />  
}

<div id="sets--container" class="sets--container">
    @if (Model.CurrentUser == null)
    {
        <!-- Instruction -->
        <section id="instructions" class="container-fluid">
            <ul class="instructions">
                <li class="instruction">
                    <div class="instruction__step">1</div>
                    <div class="instruction__text">Choose a <br>set</div>
                </li>

                <li class="instruction">
                    <div class="instruction__step">2</div>
                    <div class="instruction__text">Combine to a uniqe piece of art</div>
                </li>

                <li class="instruction">
                    <div class="instruction__step">3</div>
                    <div class="instruction__text"><button class="btn btn--green" data-toggle="modal" data-target="#loginModal">TRY IT OUT!</button></div>
                </li>
            </ul>

            <button id="closeInstructions" class="close-btn" name="close"></button>
        </section>
    }

    <!-- Page title -->
    <section class="container-fluid">
        <header class="page__title">
            <h1>Discover sets</h1>
        </header>
    </section>

    <!-- Options  -->
    <section class="options container-fluid">
        <div id="filters" class="button-group options__filter">
            <button class="options__btn--item is-checked" data-filter="*">All</button>
            <button class="options__btn--item " data-filter=".filter__photography">Photography</button>
            <button class="options__btn--item " data-filter=".filter__graffiti">Graffiti</button>
            <button class="options__btn--item " data-filter=".filter__drawing">Drawing</button>
            <button class="options__btn--item " data-filter=".filter__painting">Painting</button>
        </div>

        <div id="sorts" class="button-group options__sort">
            <button class="options__btn--item is-checked" data-sort-value="likes">Likes</button>
            <button class="options__btn--item " data-sort-value="date">Date</button>
            <button class="options__btn--item " data-sort-value="pieces">Pieces</button>
        </div>
    </section>

    <!-- List all sets  -->
    <section class="sets contianer-fluid">
        @foreach (var set in Model.Sets)
        {
            <article class="set filter__@set.Category.CategoryTitle.ToLower()" data-category="filter__@set.Category.CategoryTitle.ToLower()">
                <div class="set__image">
                    <a href="@Url.Action("Combine", "Set", new { id = @set.SetID })">
                        <div class="set__category set__category--@set.Category.CategoryTitle.ToLower()"></div>
                        <div class="set--count">@set.Pieces.Count</div>
                        <img src="@Url.Content("~/Content/img/sets/set" + set.SetID + "/" + set.SetCoverImage)" class="wiggle" alt="@set.SetTitle">
                    </a>
                </div>

                <div class="set__info">
                    <p class="set__info--title">
                        <span>@set.SetTitle</span>
                        <time data-time="@set.SetCreatedDate.ToString("yyyy-MM-dd HH:MM")" class="set__info--date date">@HtmlExtensions.dateToPrettyDate(@set.SetCreatedDate)</time>
                    </p>
                    @if (Model.CurrentUser != null && set.Likes.Any(l => l.LikeUserID == Model.CurrentUser.UserID))
                    {
                        <button class="set__info--like like--btn liked" data-setid="@set.SetID">
                            <span class="likes">@set.Likes.Count</span>
                        </button>
                    }
                    else if (Model.CurrentUser != null)
                    {
                        <button class="set__info--like like--btn" data-setid="@set.SetID">
                            <span class="likes">@set.Likes.Count</span>
                        </button>
                    }
                    else
                    {
                        <button class="set__info--like">
                            <span class="likes">@set.Likes.Count</span>
                        </button>
                    }
                </div>
            </article>
        }

    </section>

</div>